# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "DevFest Málaga '17"
email: "gdgmalaga@gmail.com"
description: "Welcome to the first edition of DevFest in Málaga: a yearly developers event in the warm Costa del Sol! December 1st, 2017"
baseurl: ""
url: "https://devfest.gdgmalaga.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-77263775-2"
googleAnalyticsSiteUrl: "devfest.gdgmalaga.com"
siteVerification: "VG_55fBpuc486kPbSclomeE7Nw7Z1fLcIFUnH9lUKzY"

# Organizer Info
organizerName: "GDG Málaga"
organizerAlternateName: "Google Developer Group Málaga"
organizerDescription: "GDG Málaga is a group of tech enthusiasts based in one of Spain’s emerging tech cities!. Our activities should not be linked to Google, the corporation."
organizerEmail: "gdgmalaga@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.meetup.com/es-ES/Google-Developer-Group-Malaga/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, malaga, cloud, assistant"
twitterAccount: "@GDGMalaga"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/Z4w3cY"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {link: "https://medium.com/@gdgmalaga", text: "Blog"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Attending"}
 - {permalink: "/cod/", text: "Code of Conduct"}

bottomNavigationLinks:
 #- {link: "https://goo.gl/Z4w3cY", text: "Become a speaker"}
rightNavigationButtons:
 #- {link: "https://goo.gl/Z4w3cY", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevFest <typeout> '17"
eventDate: "December 1st, 2017"
typeoutTextValues: '"", "Málaga"'
typeoutFallback: "Season"
heroButtons:
 #- {link: "https://goo.gl/Z4w3cY", text: "Become a speaker"}
 - {permalink: "/#subscribe", text: "Get your ticket"}
# About Block
aboutTitle: "About DevFest Málaga"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "6", specialCharacter: "+", info: "hours", detail: "of technology"}
 - {count: "17", specialCharacter: "+", info: "speakers", detail: "from Spain and beyond"}
 - {count: "4", specialCharacter: "", info: "parallel tracks", detail: "plus networking time"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Escuela Técnica Superior de Ingeniería Informática"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Blvd. Louis Pasteur, 25"
eventAddressLocality: "Málaga"
eventAddressLocalityRegion: "Spain"
eventPostalCode: "29071"
eventAddressCountry: "Spain"
eventStartTime: "2017-12-01T15:00"
eventDoorTime: "09:30"
eventEndTime: "2017-12-01T21:00"
eventPlaceCoordinates: "36.716775, -4.478202"
mapCenterCoordinates: "36.716775, -4.478152"
mapMobileCenterCoordinates: "36.716858, -4.477860"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "DevFest17"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Get notified to register"
subscribeAction: "https://malagadevfest-5f472.firebaseio.com/email.json"
subscribeInfo: "Registration will open next November 13th. The number of tickets is limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes and lunch. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "7"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  ribbon: "-20%"
  buyButtonLink: "https://devfest.gdgmalaga.com/"
  buyButtonText: "Subscribe for updates!"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-11-01T10:00"
  validThrough: "2017-11-07T23:59"
  #soldOutText: "Sold Out"
 -
  name: "Full Ticket Price"
  price: "10"
  priceCurrency: "EUR"
  ticketsNumber: "100"
  #ribbon: "-20%"
  featured: true
  buyButtonLink: "https://devfest.gdgmalaga.com/"
  buyButtonText: "Subscribe for updates!"
  ticketContentList: ["Puede traer un aparatico", "Coffe break", "Pizza"]
  validFrom: "2017-11-01T10:00"
  validThrough: "2017-11-30T23:59"
  disabled: true
  #soldOutText: "Sold Out"
 -
  name: "Student"
  price: "6"
  priceCurrency: "EUR"
  ticketsNumber: "20"
  buyButtonLink: "https://devfest.gdgmalaga.com/"
  buyButtonText: "https://devfest.gdgmalaga.com/"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-11-01T10:00"
  validThrough: "2017-11-30T23:59"
  soldOut: true
  #soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/105933283291537933167", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGMalaga", icon: "twitter"}
 - {link: "https://medium.com/@gdgmalaga", icon: "rss"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
#   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gdgmalaga@gmail.com", text: "gdgmalaga@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: ""

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "36.716775, -4.478202"
logisticsMapMobileCenterCoordinates: "36.716775, -4.478202"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Málaga"
directionDetailsCards:
 - {title: "The Venue", information: 'The School of Computer Engineering is located in the Teatinos Campus of the University of Málaga, next to the Hospital Virgen de la Victoria. All sessions, including conferences and workshops will take place in the school`s building. You will also find a cafe and free parking zones.'}
 - {title: "Public Transit", information: 'The venue is next to the stop "Clinico" of <a href="http://metromalaga.es/">Metro de Málaga</a>, that you can take from Málaga-Maria Zambrano train station – which is connected to <a href="http://www.renfe.com/viajeros/cercanias/malaga/">the Airport</a>, <a href="http://www.renfe.com">long distance trains</a> and coach/bus station. Additionally, you can reach the building using <a href="http://www.emtmalaga.es/emt-classic/home.html">the lines 8, 11 or 25 of EMT</a>, that stop in the centric street "Alameda Principal".'}
 - {title: "Hotels", information: 'Málaga is well known for its turism, and has lots of great hotels and hostels. Have a look online in your favorite travel website and choose any of the enchanting places you can find around!'}
#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
#hackathonTitle: "Hackathon"
#enableHackathon: false#

## Hackathon About Block
#aboutHackathonTitle: "Meet our themes"
#hackathonRows:
# - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
# - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
# - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}#

## Hackathon Judges Block
#judgesImage: "judges.jpg"
#judgesTitle: "Judges"#

## Hackathon Prizes Block
#prizesTitle: "Prizes"
#prizes:
# - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
# - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
# - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}#

## Hackathon Location Block
#hackathonLocationBlockTitle: "Location"
#hackathonLocationName: "Communa"
#hackathonLocationLink: "http://communa.net.ua/"
#hackathonStreetAddress: "1 Halytska St"
#hackathonAddressLocality: "Lviv"
#hackathonAddressLocalityRegion: "Lvivska"
#hackathonPostalCode: "79000"
#hackathonAddressCountry: "Ukraine"
#hackathonTimeTitle: "Hack through"
#hackathonStartTime: "2014-10-24T10:00"
#hackathonDoorTime: "09:00"
#hackathonEndTime: "2014-10-25T00:00"
#viewOnMap: "View on Google Maps"
#hackathonPlaceCoordinates: "36.716775, -4.478202"
#hackathonMapCenterCoordinates: "36.716775, -4.478202"
#hackathonMapMobileCenterCoordinates: "36.716775, -4.478202"
